[package]
name = "f76itemstuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
umya-spreadsheet = "0.7.2"
serde = "^1.0"
serde_json = "^1.0"
egui = "0.18.1"
eframe = "0.18.0"